name: NCBI-Download
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - ld_impl_linux-64=2.40
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgomp=12.2.0
  - libnsl=2.0.0
  - libsqlite=3.40.0
  - libuuid=2.32.1
  - libzlib=1.2.13
  - ncurses=6.3
  - openssl=3.1.0
  - pip=23.0.1
  - python=3.11.0
  - readline=8.1.2
  - setuptools=67.6.0
  - tk=8.6.12
  - tzdata=2022g
  - wheel=0.40.0
  - xz=5.2.6
  - pip:
    - attrs==22.2.0
    - biopython==1.81
    - coverage==7.2.1
    - iniconfig==2.0.0
    - numpy==1.24.2
    - packaging==23.0
    - pluggy==1.0.0
    - pprintpp==0.4.0
    - pycountry==22.3.5
    - pycountry-convert==0.7.2
    - pytest==7.2.2
    - pytest-cov==4.0.0
    - pytest-mock==3.10.0
    - repoze-lru==0.7
